language: python

addons:
  firefox: latest

install:
  - pip install pipenv shell
  - pipenv install
  - pip install selenium
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.24.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
script: python src/tests/functional_tests.py
